services:
  ScanWatch:
    image: ghcr.io/blakdav/scanwatch:latest
    container_name: ScanWatch
    restart: unless-stopped
    environment:
      SCANNER_IP: 172.23.24.78
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
    volumes:
      # Point this at the Paperless consume directory
      - /opt/docker/paperless/consume:/out
      - /opt/docker/scanwatch/state:/state
    ports:
      - "8080:8080"
